#!/bin/bash

if [ $# -lt 1 ];then
    echo "Usage: workerbee <id>"
    exit 1
fi

echo "$(hostname): Starting really important work using argument: $1"
time sleep $(echo "scale=2;sqrt($1)" | bc)
echo "$(hostname): Completing really important work using argument: $1"
